[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
farm_tokenization = "2dLysFbhrftGHHpGdsLeDHeCQoqXUAEtQk2qtRt7amCc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
